program Mdiapp;

uses
  Forms,
  MAIN in 'MAIN.PAS' {MainForm},
  CHILDWIN in 'CHILDWIN.PAS' {MDIChild},
  about in 'about.pas' {AboutBox},
  untConsts in 'Pub\untConsts.pas',
  untCommonUtil in 'Pub\untCommonUtil.pas',
  untCommonDm in 'Pub\untCommonDm.pas' {frmCommonDm: TDataModule},
  untSysManager in 'SysManager\untSysManager.pas' {frmSysManager: TFrame},
  untUserManager in 'SysManager\untUserManager.pas' {frmUserManager},
  untLogin in 'untLogin.pas' {frmLogin},
  untSysManagerDM in 'SysManager\Pub\untSysManagerDM.pas' {frmSysManagerDM: TDataModule},
  untRoleManager in 'SysManager\untRoleManager.pas' {frmRoleManager},
  untSetPrivilege in 'SysManager\untSetPrivilege.pas' {frmSetPrivilege},
  untMenServiceDM in 'MemService\Pub\untMenServiceDM.pas' {dmMenService: TDataModule},
  untMenServiceCenter in 'MemService\untMenServiceCenter.pas' {frmMenServiceCenter: TFrame},
  untMenManager in 'MemService\untMenManager.pas' {frmMenManager},
  untStockCenter in 'StockCenter\untStockCenter.pas' {frmStockCenter: TFrame},
  untProductCenter in 'ProductCenter\untProductCenter.pas' {frmProductCenter: TFrame},
  untDepotManagerCenter in 'DepotManagerCenter\untDepotManagerCenter.pas' {frmDepotManagerCenter: TFrame},
  untLogisticsCenter in 'LogisticsCenter\untLogisticsCenter.pas' {frmLogisticsCenter: TFrame},
  untFinanceCenter in 'FinanceCenter\untFinanceCenter.pas' {frmFinanceCenter: TFrame},
  untSupplierManager in 'StockCenter\untSupplierManager.pas' {frmSupplierManager},
  untStockCenterDM in 'StockCenter\Pub\untStockCenterDM.pas' {dmStockCenter: TDataModule},
  untBrandManager in 'StockCenter\untBrandManager.pas' {frmBrandManager},
  untCatalogManager in 'StockCenter\untCatalogManager.pas' {frmCatalogManager},
  untExpressManager in 'LogisticsCenter\untExpressManager.pas' {frmExpressManager},
  untExpressManagerDM in 'LogisticsCenter\Pub\untExpressManagerDM.pas' {dmExpressManager: TDataModule},
  untProductManager in 'StockCenter\untProductManager.pas' {frmProductManager},
  untSetRole in 'SysManager\untSetRole.pas' {frmSetRole},
  untCreateStockOrder in 'StockCenter\untCreateStockOrder.pas' {frmCreateStockOrder},
  untStockOrderManager in 'StockCenter\untStockOrderManager.pas' {frmStockOrderManager},
  untExceptStockOrder in 'StockCenter\untExceptStockOrder.pas' {frmExceptStockOrder},
  untPriceEdit in 'ProductCenter\untPriceEdit.pas' {frmPriceEdit},
  untShelfManager in 'ProductCenter\untShelfManager.pas' {frmShelfManager},
  untSellStat in 'ProductCenter\untSellStat.pas' {frmSellStat},
  untCreateOrder in 'MemService\untCreateOrder.pas' {frmCreateOrder},
  untOrderManager in 'MemService\untOrderManager.pas' {frmOrderManager},
  untSendBackManager in 'MemService\untSendBackManager.pas' {frmSendBackManager},
  untDispatchingQuery in 'MemService\untDispatchingQuery.pas' {frmDispatchingQuery},
  untProductIntoDepot in 'DepotManagerCenter\untProductIntoDepot.pas' {frmProductIntoDepot},
  untDepotPositionManager in 'DepotManagerCenter\untDepotPositionManager.pas' {frmDepotPositionManager},
  untFinanceOrderManager in 'FinanceCenter\untFinanceOrderManager.pas' {frmFinanceOrderManager},
  untFinanceSendBackManager in 'FinanceCenter\untFinanceSendBackManager.pas' {frmFinanceSendBackManager},
  untDepotCenterDM in 'DepotManagerCenter\Pub\untDepotCenterDM.pas' {dmDepotCenter: TDataModule},
  untStOAddProduct in 'StockCenter\untStOAddProduct.pas' {frmStOAddProduct},
  untAddOrderProduct in 'MemService\untAddOrderProduct.pas' {frmAddOrderProduct},
  untOrderInfo in 'MemService\untOrderInfo.pas' {frmOrderInfo},
  untStockOrderInfo in 'StockCenter\untStockOrderInfo.pas' {frmStockOrderInfo},
  untPIDManager in 'DepotManagerCenter\untPIDManager.pas' {frmPIDManager},
  untPIDOpt in 'DepotManagerCenter\untPIDOpt.pas' {frmPIDOpt},
  untEStOInfo in 'StockCenter\untEStOInfo.pas' {frmEStOInfo},
  untEStockOrder in 'DepotManagerCenter\untEStockOrder.pas' {frmEStockOrder},
  untEStOrderInfo in 'DepotManagerCenter\untEStOrderInfo.pas' {frmEStOrderInfo},
  untODpManager in 'DepotManagerCenter\untODpManager.pas' {frmODpManager},
  untOSBackManager in 'DepotManagerCenter\untOSBackManager.pas' {frmOSBackManager},
  untPCenterDM in 'ProductCenter\Pub\untPCenterDM.pas' {dmPCenter: TDataModule},
  untFCenterDM in 'FinanceCenter\Pub\untFCenterDM.pas' {dmFCenter: TDataModule},
  untSCatInput in 'ProductCenter\untSCatInput.pas' {frmSCatInput},
  untPODManager in 'DepotManagerCenter\untPODManager.pas' {frmPODManager},
  untPODOpt in 'DepotManagerCenter\untPODOpt.pas' {frmPODOpt},
  untSetPrice in 'ProductCenter\untSetPrice.pas' {frmSetPrice},
  untProductEdit in 'ProductCenter\untProductEdit.pas' {frmProductEdit},
  untSetPicture in 'ProductCenter\untSetPicture.pas' {frmSetPicture},
  untEStOPDel in 'StockCenter\untEStOPDel.pas' {frmEStOPDel},
  untEStOPUpdate in 'StockCenter\untEStOPUpdate.pas' {frmEStOPUpdate},
  untFOrderInfo in 'FinanceCenter\untFOrderInfo.pas' {frmFOrderInfo},
  untSetPDetail in 'ProductCenter\untSetPDetail.pas' {frmSetPDetail},
  untExpressInfo in 'DepotManagerCenter\untExpressInfo.pas' {frmExpressInfo},
  untSOOutDepot in 'DepotManagerCenter\untSOOutDepot.pas' {frmSOOutDepot},
  untSetCOPNum in 'MemService\untSetCOPNum.pas' {frmSetCOPNum},
  untSetBPicture in 'StockCenter\untSetBPicture.pas' {frmSetBPicture},
  untCreateROrder in 'MemService\untCreateROrder.pas' {frmCreateROrder},
  untSetROPNum in 'MemService\untSetROPNum.pas' {frmSetROPNum},
  untSBOInfo in 'MemService\untSBOInfo.pas' {frmSBOInfo},
  untROInfo in 'DepotManagerCenter\untROInfo.pas' {frmROInfo},
  untFSBOInfo in 'FinanceCenter\untFSBOInfo.pas' {frmFSBOInfo},
  untStockStat in 'DepotManagerCenter\untStockStat.pas' {frmStockStat},
  untSelectProduct in 'StockCenter\untSelectProduct.pas' {frmSelectProduct},
  untSetIndexPrd in 'ProductCenter\untSetIndexPrd.pas' {frmSetIndexPrd},
  untSetShelfPrice in 'ProductCenter\untSetShelfPrice.pas' {frmSetShelfPrice},
  untIniIO in 'Pub\untIniIO.pas',
  untAllocatePrint in 'DepotManagerCenter\untAllocatePrint.pas' {frmAllocatePrint},
  untSetConfig in 'untSetConfig.pas' {frmSetConfig},
  untCInvoice in 'MemService\untCInvoice.pas' {frmCInvoice},
  untShowSql in 'untShowSql.pas' {frmShowSql},
  untSelSameSn in 'ProductCenter\untSelSameSn.pas' {frmSelSameSn},
  untCSoRList in 'MemService\untCSoRList.pas' {frmCSoRList},
  untFinanceStat in 'FinanceCenter\untFinanceStat.pas' {frmFinanceStat},
  untShowPDetailPic in 'ProductCenter\untShowPDetailPic.pas' {frmShowPDetailPic},
  untScatProductList in 'ProductCenter\untScatProductList.pas' {frmScatProductList},
  untSelectMem in 'MemService\untSelectMem.pas' {frmSelectMem},
  untReviewManager in 'MemService\untReviewManager.pas' {frmReviewManager},
  untProductDepotManager in 'MemService\untProductDepotManager.pas' {frmProductDepotManager};

{$R *.RES}

begin
  Application.Initialize;
  Application.Title := 'VEGAGA后台管理系统';
  Application.CreateForm(TfrmLogin, frmLogin);
  Application.Run;
end.
